version: '2'

services:
  app:
    build:
      context:  ./app
      dockerfile: Dockerfile
    expose:
      - "5000"

  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - app